# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetDescription', models.CharField(max_length=1024, null=True)),
                ('assetNumber', models.IntegerField()),
                ('assetIsActive', models.BooleanField(default=True)),
                ('assetOwnerDescription', models.CharField(max_length=1024, null=True)),
                ('assetOwnerKey', models.CharField(max_length=1024, null=True)),
                ('assetRegistryCode', models.CharField(max_length=255, null=True)),
                ('assetProviderAcc', models.CharField(max_length=255, null=True)),
                ('assetProviderAccPassword', models.CharField(max_length=255, null=True)),
                ('assetStoragePassword', models.CharField(max_length=255, null=True)),
                ('dciUserPassword', models.CharField(max_length=50, null=True)),
                ('dciConfigPassword', models.CharField(max_length=50, null=True)),
                ('dciFrequencyUnit', models.CharField(max_length=50, null=True)),
                ('dciFrequencyValue', models.IntegerField(null=True)),
                ('dciQtyVps', models.IntegerField(null=True)),
                ('dciTolerancePosition', models.IntegerField(default=50)),
                ('dciToleranceRotation', models.IntegerField(default=10)),
                ('dciIMEI', models.CharField(max_length=50, null=True)),
                ('dciModel', models.CharField(max_length=50, null=True)),
                ('dciWifiMAC', models.CharField(max_length=50, null=True)),
                ('dciRemotePassword', models.CharField(max_length=50, null=True)),
                ('dciDciBoxWifiModel', models.CharField(max_length=50, null=True)),
                ('dciDciBoxWifiSSID', models.CharField(max_length=50, null=True)),
                ('dciDciBoxWifiPassword', models.CharField(max_length=50, null=True)),
                ('dciDciBoxWifiAdministrator', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoMillisSinceEpoch', models.BigIntegerField()),
                ('photoVpNumber', models.IntegerField()),
                ('photoAssetNumber', models.IntegerField()),
                ('photoStorageURL', models.CharField(max_length=255)),
                ('photoImageLatitude', models.FloatField()),
                ('photoImageLongitude', models.FloatField()),
                ('photoDBTimeStamp', models.DateTimeField(auto_now_add=True)),
                ('photoTimeStamp', models.DateTimeField()),
                ('photoProcessed', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valValueEvaluated', models.FloatField()),
                ('valValueEvaluatedEntryDBTimeStamp', models.DateTimeField(auto_now_add=True)),
                ('tagStateEvaluated', models.IntegerField()),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymensor.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagDescription', models.CharField(max_length=1024)),
                ('tagNumber', models.IntegerField()),
                ('tagIsActive', models.BooleanField(default=True)),
                ('tagListNumber', models.IntegerField(null=True)),
                ('tagQuestion', models.CharField(max_length=1024)),
                ('tagLowRedValue', models.FloatField(null=True)),
                ('tagLowYellow', models.FloatField(null=True)),
                ('tagLowGreen', models.FloatField(null=True)),
                ('tagExpValue', models.FloatField(null=True)),
                ('tagHighGreen', models.FloatField(null=True)),
                ('tagHighYellow', models.FloatField(null=True)),
                ('tagHighRed', models.FloatField(null=True)),
                ('tagType', models.CharField(max_length=50, null=True)),
                ('tagIsDependantOfMasterTagNumber', models.IntegerField(null=True)),
                ('tagMaxLagFromMasterTagInMillis', models.BigIntegerField(null=True)),
                ('tagMaxLagFromSlaveTagsInMillis', models.BigIntegerField(null=True)),
                ('tagIsSetForSpecialCheck', models.BooleanField(default=False)),
                ('tagSpecialCheckAcceptableDiscrepancy', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valValue', models.FloatField()),
                ('valValueEntryDBTimeStamp', models.DateTimeField(auto_now_add=True)),
                ('valEvalStatus', models.CharField(max_length=50, null=True)),
                ('tagStateResultingFromValValueStatus', models.IntegerField()),
                ('processedTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymensor.ProcessedTag')),
                ('processorUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpDescription', models.CharField(max_length=1024)),
                ('vpNumber', models.IntegerField()),
                ('vpIsActive', models.BooleanField(default=True)),
                ('vpListNumber', models.IntegerField(null=True)),
                ('vpStdPhotoStorageURL', models.CharField(max_length=255)),
                ('vpStdTagDescPhotoStorageURL', models.CharField(max_length=255, null=True)),
                ('vpStdMarkerPhotoStorageURL', models.CharField(max_length=255, null=True)),
                ('vpMarkerId', models.IntegerField(null=True)),
                ('vpStdIdMarkerPhotoStorageURL', models.CharField(max_length=255, null=True)),
                ('vpConfiguredMillis', models.BigIntegerField(null=True)),
                ('vpXDistance', models.IntegerField(null=True)),
                ('vpYDistance', models.IntegerField(null=True)),
                ('vpZDistance', models.IntegerField(null=True)),
                ('vpXRotation', models.IntegerField(null=True)),
                ('vpYRotation', models.IntegerField(null=True)),
                ('vpZRotation', models.IntegerField(null=True)),
                ('vpMarkerlessMarkerWidth', models.IntegerField(null=True)),
                ('vpMarkerlessMarkerHeigth', models.IntegerField(null=True)),
                ('vpIsAmbiguos', models.BooleanField(default=False)),
                ('vpIsSuperSingle', models.BooleanField(default=False)),
                ('vpIsSuperMultiple', models.BooleanField(default=False)),
                ('vpFlashTorchIsOn', models.BooleanField(default=False)),
                ('vpSuperIdIsSmall', models.BooleanField(default=False)),
                ('vpSuperIdIsMedium', models.BooleanField(default=False)),
                ('vpSuperIdIsLarge', models.BooleanField(default=False)),
                ('vpSuperMarkerId', models.IntegerField(null=True)),
                ('vpFrequencyUnit', models.CharField(max_length=50, null=True)),
                ('vpFrequencyValue', models.IntegerField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymensor.Asset')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='vp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymensor.Vp'),
        ),
        migrations.AddField(
            model_name='processedtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymensor.Tag'),
        ),
        migrations.AddField(
            model_name='photo',
            name='vp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mymensor.Vp'),
        ),
    ]
