# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 20:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mymensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetNumber', models.IntegerField()),
                ('assetIsActive', models.BooleanField(default=True)),
                ('assetDescription', models.CharField(max_length=1024)),
                ('assetRegistryCode', models.CharField(max_length=255)),
                ('assetProviderAcc', models.CharField(max_length=255)),
                ('assetProviderAccPassword', models.CharField(max_length=255)),
                ('assetStoragePassword', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AssetOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetOwnerNumber', models.IntegerField()),
                ('assetOwnerIsActive', models.BooleanField(default=True)),
                ('assetOwnerDescription', models.CharField(max_length=1024)),
                ('assetOwnerLogoURL', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dciNumber', models.IntegerField()),
                ('dciIsActive', models.BooleanField(default=True)),
                ('dciUserPassword', models.CharField(max_length=50, null=True)),
                ('dciConfigPassword', models.CharField(max_length=50, null=True)),
                ('dciFrequencyUnit', models.CharField(max_length=50)),
                ('dciFrequencyValue', models.IntegerField()),
                ('dciQtyVps', models.IntegerField(null=True)),
                ('dciTolerancePosition', models.IntegerField(default=50)),
                ('dciToleranceRotation', models.IntegerField(default=10)),
                ('dciIMEI', models.CharField(max_length=50, null=True)),
                ('dciModel', models.CharField(max_length=50, null=True)),
                ('dciWifiMAC', models.CharField(max_length=50, null=True)),
                ('dciRemotePassword', models.CharField(max_length=50, null=True)),
                ('dciDciBoxWifiModel', models.CharField(max_length=50, null=True)),
                ('dciDciBoxWifiSSID', models.CharField(max_length=50, null=True)),
                ('dciDciBoxWifiPassword', models.CharField(max_length=50, null=True)),
                ('dciDciBoxWifiAdministrator', models.CharField(max_length=50, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymensor.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valValueEvaluated', models.FloatField()),
                ('valValueEvaluatedEntryDBTimeStamp', models.DateTimeField(auto_now_add=True)),
                ('tagStateEvaluated', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagNumber', models.IntegerField()),
                ('tagIsActive', models.BooleanField(default=True)),
                ('tagDescription', models.CharField(max_length=1024)),
                ('tagQuestion', models.CharField(max_length=1024)),
                ('tagLowRedValue', models.FloatField(null=True)),
                ('tagLowYellow', models.FloatField(null=True)),
                ('tagLowGreen', models.FloatField(null=True)),
                ('tagExpValue', models.FloatField(null=True)),
                ('tagHighGreen', models.FloatField(null=True)),
                ('tagHighYellow', models.FloatField(null=True)),
                ('tagHighRed', models.FloatField(null=True)),
                ('tagType', models.CharField(max_length=50, null=True)),
                ('tagIsDependantOfMasterTagNumber', models.IntegerField(null=True)),
                ('tagMaxLagFromMasterTagInMillis', models.BigIntegerField(null=True)),
                ('tagMaxLagFromSlaveTagsInMillis', models.BigIntegerField(null=True)),
                ('tagIsSetForSpecialCheck', models.BooleanField(default=False)),
                ('tagSpecialCheckAcceptableDiscrepancy', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valValue', models.FloatField()),
                ('valValueEntryDBTimeStamp', models.DateTimeField(auto_now_add=True)),
                ('valEvalStatus', models.CharField(max_length=50, null=True)),
                ('tagStateResultingFromValValue', models.IntegerField()),
                ('processedTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymensor.ProcessedTag')),
                ('processorUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpNumber', models.IntegerField()),
                ('vpIsActive', models.BooleanField(default=True)),
                ('vpListNumber', models.IntegerField(null=True)),
                ('vpDescription', models.CharField(max_length=1024)),
                ('vpStdPhotoStorageURL', models.CharField(max_length=255)),
                ('vpStdTagDescPhotoStorageURL', models.CharField(max_length=255, null=True)),
                ('vpStdMarkerPhotoStorageURL', models.CharField(max_length=255, null=True)),
                ('vpMarkerId', models.IntegerField(null=True)),
                ('vpStdIdMarkerPhotoStorageURL', models.CharField(max_length=255, null=True)),
                ('vpConfiguredMillis', models.BigIntegerField(null=True)),
                ('vpXDistance', models.IntegerField(null=True)),
                ('vpYDistance', models.IntegerField(null=True)),
                ('vpZDistance', models.IntegerField(null=True)),
                ('vpXRotation', models.IntegerField(null=True)),
                ('vpYRotation', models.IntegerField(null=True)),
                ('vpZRotation', models.IntegerField(null=True)),
                ('vpMarkerlessMarkerWidth', models.IntegerField(null=True)),
                ('vpMarkerlessMarkerHeigth', models.IntegerField(null=True)),
                ('vpIsAmbiguos', models.BooleanField(default=False)),
                ('vpIsSuperSingle', models.BooleanField(default=False)),
                ('vpIsSuperMultiple', models.BooleanField(default=False)),
                ('vpFlashTorchIsOn', models.BooleanField(default=False)),
                ('vpSuperIdIsSmall', models.BooleanField(default=False)),
                ('vpSuperIdIsMedium', models.BooleanField(default=False)),
                ('vpSuperIdIsLarge', models.BooleanField(default=False)),
                ('vpSuperMarkerId', models.IntegerField(null=True)),
                ('vpFrequencyUnit', models.CharField(max_length=50, null=True)),
                ('vpFrequencyValue', models.IntegerField(null=True)),
                ('dci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymensor.Dci')),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='photoDBTimeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='vp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymensor.Vp'),
        ),
        migrations.AddField(
            model_name='processedtag',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymensor.Photo'),
        ),
        migrations.AddField(
            model_name='processedtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymensor.Tag'),
        ),
        migrations.AddField(
            model_name='asset',
            name='assetOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymensor.AssetOwner'),
        ),
        migrations.AddField(
            model_name='photo',
            name='vp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mymensor.Vp'),
            preserve_default=False,
        ),
    ]
