# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0002_asset_assetowneruserid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonSNSNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snsMessage', models.CharField(max_length=4096, null=True)),
                ('snsMessageId', models.CharField(max_length=1024, null=True)),
                ('snsSignature', models.CharField(max_length=1024, null=True)),
                ('snsSubject', models.CharField(max_length=1024, null=True)),
                ('snsTimestamp', models.CharField(max_length=1024, null=True)),
                ('snsTopicArn', models.CharField(max_length=1244, null=True)),
                ('snsType', models.CharField(max_length=1024, null=True)),
                ('snsUnsubscribeURL', models.CharField(max_length=1024, null=True)),
            ],
        ),
    ]
