# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0002_auto_20160816_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='value',
            old_name='tagStateResultingFromValValue',
            new_name='tagStateResultingFromValValueStatus',
        ),
    ]
