# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0003_amazonsnsnotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='snsMessage',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='snsMessageId',
            new_name='MessageId',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='snsSignature',
            new_name='Signature',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='snsSubject',
            new_name='SignatureVersion',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='snsTimestamp',
            new_name='Subject',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='snsType',
            new_name='SubscribeURL',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='snsUnsubscribeURL',
            new_name='Timestamp',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='snsTopicArn',
            new_name='TopicArn',
        ),
        migrations.AddField(
            model_name='amazonsnsnotification',
            name='Token',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='amazonsnsnotification',
            name='Type',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='amazonsnsnotification',
            name='UnsubscribeURL',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
