# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0003_auto_20160816_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='vp',
        ),
    ]
