# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0004_auto_20160914_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='MessageId',
            new_name='messageId',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='Signature',
            new_name='signature',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='SignatureVersion',
            new_name='signatureVersion',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='SubscribeURL',
            new_name='subscribeURL',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='Timestamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='Token',
            new_name='token',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='TopicArn',
            new_name='topicArn',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='UnsubscribeURL',
            new_name='unsubscribeURL',
        ),
    ]
