# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0004_remove_photo_vp'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='vp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mymensor.Vp'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetDescription',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetProviderAcc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetProviderAccPassword',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetRegistryCode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetStoragePassword',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assetowner',
            name='assetOwnerDescription',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
