# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0005_auto_20160914_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='message',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='messageId',
            new_name='MessageId',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='signature',
            new_name='Signature',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='signatureVersion',
            new_name='SignatureVersion',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='subject',
            new_name='Subject',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='subscribeURL',
            new_name='SubscribeURL',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='timestamp',
            new_name='Timestamp',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='token',
            new_name='Token',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='topicArn',
            new_name='TopicArn',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='type',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='amazonsnsnotification',
            old_name='unsubscribeURL',
            new_name='UnsubscribeURL',
        ),
    ]
