# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0005_auto_20160817_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='assetOwner',
        ),
        migrations.RemoveField(
            model_name='dci',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='vp',
        ),
        migrations.RemoveField(
            model_name='processedtag',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='processedtag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='vp',
        ),
        migrations.RemoveField(
            model_name='value',
            name='processedTag',
        ),
        migrations.RemoveField(
            model_name='value',
            name='processorUserId',
        ),
        migrations.RemoveField(
            model_name='vp',
            name='dci',
        ),
    ]
