# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 10:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mymensor', '0006_auto_20160817_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assetOwner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mymensor.AssetOwner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dci',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mymensor.Asset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='vp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mymensor.Vp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processedtag',
            name='photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mymensor.Photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processedtag',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mymensor.Tag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='vp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mymensor.Vp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='value',
            name='processedTag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mymensor.ProcessedTag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='value',
            name='processorUserId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vp',
            name='dci',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mymensor.Dci'),
            preserve_default=False,
        ),
    ]
