# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0006_auto_20160914_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenIdOuath2RedirectCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50, null=True)),
                ('code', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
