# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0007_openidouath2redirectcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenIdOuath2RedirectCode',
        ),
    ]
