# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-18 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0007_auto_20160817_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tagListNumber',
            field=models.IntegerField(null=True),
        ),
    ]
