# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-22 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0008_tag_taglistnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='dci',
            name='dciDescription',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
