# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-22 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0009_dci_dcidescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyMensorConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='dciNumber', chained_model_field='dciNumber', on_delete=django.db.models.deletion.CASCADE, to='mymensor.Asset')),
                ('assetOwner', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='assetNumber', chained_model_field='assetNumber', on_delete=django.db.models.deletion.CASCADE, to='mymensor.AssetOwner')),
                ('dci', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='vpNumber', chained_model_field='vpNumber', on_delete=django.db.models.deletion.CASCADE, to='mymensor.Dci')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymensor.Tag')),
                ('vp', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='tagNumber', chained_model_field='tagNumber', on_delete=django.db.models.deletion.CASCADE, to='mymensor.Vp')),
            ],
        ),
    ]
