# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-22 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0010_mymensorconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymensorconfiguration',
            name='asset',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='assetOwner', chained_model_field='assetOwner', on_delete=django.db.models.deletion.CASCADE, to='mymensor.Asset'),
        ),
        migrations.AlterField(
            model_name='mymensorconfiguration',
            name='assetOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymensor.AssetOwner'),
        ),
        migrations.AlterField(
            model_name='mymensorconfiguration',
            name='dci',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='asset', chained_model_field='asset', on_delete=django.db.models.deletion.CASCADE, to='mymensor.Dci'),
        ),
        migrations.AlterField(
            model_name='mymensorconfiguration',
            name='tag',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='vp', chained_model_field='vp', on_delete=django.db.models.deletion.CASCADE, to='mymensor.Tag'),
        ),
        migrations.AlterField(
            model_name='mymensorconfiguration',
            name='vp',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='dci', chained_model_field='dci', on_delete=django.db.models.deletion.CASCADE, to='mymensor.Vp'),
        ),
    ]
