# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0011_auto_20160822_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dci',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='mymensorconfiguration',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='mymensorconfiguration',
            name='assetOwner',
        ),
        migrations.RemoveField(
            model_name='mymensorconfiguration',
            name='dci',
        ),
        migrations.RemoveField(
            model_name='mymensorconfiguration',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='mymensorconfiguration',
            name='vp',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='assetOwner',
        ),
        migrations.RemoveField(
            model_name='vp',
            name='dci',
        ),
        migrations.AddField(
            model_name='asset',
            name='assetOwnerDescription',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='assetOwnerKey',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='dciConfigPassword',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='dciDciBoxWifiAdministrator',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='dciDciBoxWifiModel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='dciDciBoxWifiPassword',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='dciDciBoxWifiSSID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='dciFrequencyUnit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='dciFrequencyValue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='dciIMEI',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='dciModel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='dciQtyVps',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='dciRemotePassword',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='dciTolerancePosition',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='dciToleranceRotation',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='dciUserPassword',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='dciWifiMAC',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vp',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mymensor.Asset'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AssetOwner',
        ),
        migrations.DeleteModel(
            name='Dci',
        ),
        migrations.DeleteModel(
            name='MyMensorConfiguration',
        ),
    ]
