# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-26 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0011_auto_20161226_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='mediaContentType',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
