# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0012_auto_20160901_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photoAssetOwnerNumber',
        ),
    ]
