# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0012_media_mediacontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonS3Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventVersion', models.CharField(max_length=1024, null=True)),
                ('eventSource', models.CharField(max_length=1024, null=True)),
                ('awsRegion', models.CharField(max_length=1024, null=True)),
                ('eventTime', models.CharField(max_length=1024, null=True)),
                ('eventName', models.CharField(max_length=1024, null=True)),
                ('userIdentity_principalId', models.CharField(max_length=1024, null=True)),
                ('requestParameters_sourceIPAddress', models.CharField(max_length=1024, null=True)),
                ('responseElements_x_amz_request_id', models.CharField(max_length=1024, null=True)),
                ('responseElements_x_amz_id_2', models.CharField(max_length=1024, null=True)),
                ('s3_s3SchemaVersion', models.CharField(max_length=1024, null=True)),
                ('s3_configurationId', models.CharField(max_length=1024, null=True)),
                ('s3_bucket_name', models.CharField(max_length=1024, null=True)),
                ('s3_bucket_ownerIdentity_principalId', models.CharField(max_length=1024, null=True)),
                ('s3_bucket_arn', models.CharField(max_length=1024, null=True)),
                ('s3_object_key', models.CharField(max_length=1024, null=True)),
                ('s3_object_size', models.CharField(max_length=1024, null=True)),
                ('s3_object_eTag', models.CharField(max_length=1024, null=True)),
                ('s3_object_versionId', models.CharField(max_length=1024, null=True)),
                ('s3_object_sequencer', models.CharField(max_length=1024, null=True)),
            ],
        ),
    ]
