# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0013_amazons3message'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonsnsnotification',
            name='s3_object_key',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
