# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-07 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0013_remove_photo_photoassetownernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='vp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mymensor.Vp'),
        ),
    ]
