# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0014_amazonsnsnotification_s3_object_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonsnsnotification',
            name='Message',
        ),
    ]
