# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0015_remove_amazonsnsnotification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonsnsnotification',
            name='s3_object_key',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
