# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-06 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0017_auto_20170105_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='mediaAltitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='mediaAssetNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='mediaContentType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='mediaLatitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='mediaLocMethod',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='mediaLocMillis',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='mediaLocPrecisionInMeters',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='mediaLongitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='mediaMillisSinceEpoch',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='mediaMymensorAccount',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='mediaStorageURL',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='mediaTimeStamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='mediaVpNumber',
            field=models.IntegerField(null=True),
        ),
    ]
