# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0018_auto_20170106_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='mediaObjectS3Key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='mediaStorageURL',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
