# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0019_auto_20170109_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazons3message',
            name='amazonSNSNotification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mymensor.AmazonSNSNotification'),
        ),
        migrations.AddField(
            model_name='media',
            name='amazonS3Message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mymensor.AmazonS3Message'),
        ),
    ]
