# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0022_media_mediastateevaluated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assetDciQtyVps',
            field=models.IntegerField(default=31),
        ),
    ]
