# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0025_tagstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagStatusDjango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'mymensor_tagstatusdjango',
                'managed': False,
            },
        ),
    ]
