# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0028_tagstatustable_statusdbtimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagstatustable',
            name='statusMediaMillisSinceEpoch',
            field=models.BigIntegerField(null=True),
        ),
    ]
