# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 19:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mymensor', '0029_tagstatustable_statusmediamillissinceepoch'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileSetupBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backupDescription', models.CharField(max_length=1024, null=True)),
                ('backupName', models.CharField(max_length=255, null=True)),
                ('backupDBTimeStamp', models.DateTimeField(auto_now_add=True)),
                ('backupOwner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
