# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0030_mobilesetupbackup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tagHighGreen',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tagLowGreen',
        ),
    ]
