# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0031_auto_20170215_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tagLowRedValue',
            new_name='tagLowRed',
        ),
    ]
