# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0032_auto_20170215_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagbbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagbboxType', models.CharField(default='rect', max_length=50)),
                ('tagbboxX', models.FloatField(null=True)),
                ('tagbboxY', models.FloatField(null=True)),
                ('tagbboxWidth', models.FloatField(null=True)),
                ('tagbboxHeight', models.FloatField(null=True)),
                ('tagbboxStroke', models.CharField(default='#000', max_length=50)),
                ('tagbboxStrokeWidth', models.IntegerField(default=2)),
                ('tagbboxFill', models.CharField(default='none', max_length=50)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymensor.Tag')),
            ],
        ),
    ]
