# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0033_tagbbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assetOwnerIdentityId',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
