# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0034_asset_assetowneridentityid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagstatustable',
            name='statusDBTimeStamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Processing Time'),
        ),
        migrations.AlterField(
            model_name='tagstatustable',
            name='statusMediaTimeStamp',
            field=models.DateTimeField(null=True, verbose_name='Media Time'),
        ),
        migrations.AlterField(
            model_name='tagstatustable',
            name='statusTagDescription',
            field=models.CharField(max_length=1024, verbose_name='Tag Description'),
        ),
        migrations.AlterField(
            model_name='tagstatustable',
            name='statusTagNumber',
            field=models.IntegerField(verbose_name='Tag#'),
        ),
        migrations.AlterField(
            model_name='tagstatustable',
            name='statusTagStateEvaluated',
            field=models.CharField(choices=[('NP', 'NOT PROCESSED'), ('PR', 'PROCESSED'), ('LR', 'LOW RED'), ('LY', 'LOW YELLOW'), ('GR', 'GREEN'), ('HY', 'HIGH YELLOW'), ('HR', 'HIGH RED')], max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tagstatustable',
            name='statusTagUnit',
            field=models.CharField(max_length=50, null=True, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='tagstatustable',
            name='statusValValueEvaluated',
            field=models.FloatField(verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='tagstatustable',
            name='statusVpDescription',
            field=models.CharField(max_length=1024, verbose_name='VP Description'),
        ),
        migrations.AlterField(
            model_name='tagstatustable',
            name='statusVpNumber',
            field=models.IntegerField(verbose_name='VP#'),
        ),
    ]
