# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0038_auto_20170225_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='mediaStateEvaluated',
            field=models.CharField(choices=[('NP', 'NOT PROCESSED'), ('PR', 'PROCESSED'), ('LR', 'LOW RED'), ('LY', 'LOW YELLOW'), ('GR', 'GREEN'), ('HY', 'HIGH YELLOW'), ('HR', 'HIGH RED')], max_length=50, null=True),
        ),
    ]
