# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0038_auto_20170225_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assetDciFrequencyUnit',
            field=models.CharField(default='millis', max_length=50, verbose_name='Capture frequency unit'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetDciFrequencyValue',
            field=models.IntegerField(default=20000, verbose_name='Capture frequency value'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetDescription',
            field=models.CharField(max_length=1024, null=True, verbose_name='Asset Description'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetOwnerDescription',
            field=models.CharField(max_length=1024, null=True, verbose_name='Asset Owner Description'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetOwnerKey',
            field=models.CharField(max_length=1024, null=True, verbose_name='Asset Owner Key'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetRegistryCode',
            field=models.CharField(max_length=255, null=True, verbose_name='Asset Registry code'),
        ),
    ]
