# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 11:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0039_auto_20170227_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assetDciQtyVps',
            field=models.IntegerField(default=31, verbose_name='Quantity of Vps in Asset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetDciTolerancePosition',
            field=models.IntegerField(default=50, verbose_name='Position tolerance for capture'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetDciToleranceRotation',
            field=models.IntegerField(default=10, verbose_name='Rotation tolerance for capture'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetIsActive',
            field=models.BooleanField(default=True, verbose_name='Asset is active'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetNumber',
            field=models.IntegerField(verbose_name='Asset Number'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetOwner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Asset Owner'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetOwnerIdentityId',
            field=models.CharField(max_length=1024, null=True, verbose_name='Asset Owner Identity Id'),
        ),
    ]
