# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 09:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mymensor', '0042_auto_20170301_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twtAccessTokenKey', models.CharField(max_length=1024, null=True, verbose_name='Twitter Auth Access Token Key')),
                ('twtAccessTokenSecret', models.CharField(max_length=1024, null=True, verbose_name='Twitter Auth Access Token Secret')),
                ('twtOwner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Twitter Owner')),
            ],
        ),
    ]
