# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0044_vp_vpissharedtotwitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vp',
            name='vpIsSharedToTwitter',
            field=models.BooleanField(default=False, verbose_name='share vp to Twitter'),
        ),
    ]
