# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0047_facebookaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='vp',
            name='vpIsSharedToFacebook',
            field=models.BooleanField(default=False, verbose_name='share all of this vp captures to the Facebook Account set.'),
        ),
        migrations.AlterField(
            model_name='vp',
            name='vpIsSharedToTwitter',
            field=models.BooleanField(default=False, verbose_name='share all of this vp captures to the Twitter Account set.'),
        ),
    ]
