# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0048_auto_20170410_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookaccount',
            name='fbShortTermAccesTokenIssuedAt',
        ),
        migrations.AddField(
            model_name='facebookaccount',
            name='fbLongTermAccesTokenExpiresIn',
            field=models.CharField(max_length=255, null=True, verbose_name='Facebook Long Term Access Token Expires In Seconds'),
        ),
    ]
