# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0049_auto_20170411_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='vp',
            name='vpShareEmail',
            field=models.EmailField(max_length=254, null=True, verbose_name='send all of this vp captures to the following email.'),
        ),
        migrations.AlterField(
            model_name='vp',
            name='vpIsSharedToFacebook',
            field=models.BooleanField(default=False, verbose_name='share all of this vp captures to the Facebook Account configured.'),
        ),
        migrations.AlterField(
            model_name='vp',
            name='vpIsSharedToTwitter',
            field=models.BooleanField(default=False, verbose_name='share all of this vp captures to the Twitter Account configured.'),
        ),
    ]
