# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0051_auto_20170427_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vp',
            name='vpShareEmail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='send all of this vp captures to the following email.'),
        ),
    ]
