# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0052_auto_20170427_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='mediaRemark',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
