# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0053_media_mediaremark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assetDciFrequencyValue',
            field=models.IntegerField(default=20000, verbose_name='Minimum capture frequency value'),
        ),
        migrations.AlterField(
            model_name='vp',
            name='vpFrequencyValue',
            field=models.IntegerField(null=True, verbose_name='minimum vp capture frequency'),
        ),
    ]
