# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0054_auto_20170611_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assetDciClientSoftwareType',
            field=models.CharField(max_length=255, null=True, verbose_name='Client Software Type'),
        ),
    ]
