# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 12:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mymensor', '0055_asset_assetdciclientsoftwaretype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BraintreeCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('braintreecustomerCustomerId', models.CharField(max_length=1024, null=True)),
                ('braintreecustomerPaymentMethodNonce', models.CharField(max_length=1024, null=True)),
                ('braintreecustomerPaymentMethodToken', models.CharField(max_length=1024, null=True)),
                ('braintreecustomerPlanId', models.CharField(max_length=1024, null=True)),
                ('braintreecustomerMerchantAccId', models.CharField(choices=[('mymensorUSD', 'USD'), ('mymensorEUR', 'EUR'), ('mymensorBRL', 'BRL')], default='mymensorUSD', max_length=1024)),
                ('braintreecustomerPrice', models.FloatField(null=True)),
                ('braintreecustomerSubscriptionId', models.CharField(max_length=1024, null=True)),
                ('braintreecustomerSubscriptionStatus', models.CharField(max_length=50, null=True)),
                ('braintreecustomerCustomerCreated', models.NullBooleanField()),
                ('braintreecustomerOwner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
