# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0059_auto_20170623_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymprice',
            name='mympriceBillingExpirationInCycleQty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mymprice',
            name='mympriceDiscountPercentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
