# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0060_auto_20170623_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='assetDciClientSoftwareType',
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetOwnerIdentityId',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Asset Owner Identity Id'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetOwnerKey',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Asset Owner Key'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetRegistryCode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Asset Registry code'),
        ),
    ]
