# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0061_auto_20170623_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assetDciClientSoftwareType',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Software Type'),
        ),
    ]
