# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0063_auto_20170623_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymprice',
            name='mympriceCurrency',
            field=models.CharField(choices=[('mymensorUSD', 'USD'), ('mymensorEUR', 'EUR'), ('mymensorBRL', 'BRL'), ('gfng', 'EUR')], max_length=4),
        ),
    ]
