# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0064_auto_20170623_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='BraintreeMerchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('braintreemerchMerchId', models.CharField(max_length=1024, null=True)),
                ('braintreemerchCurrency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BRL', 'BRL')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BraintreePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('braintreeplanPlanName', models.CharField(max_length=1024)),
                ('braintreeplanPlanId', models.CharField(max_length=1024)),
                ('braintreeplanBillingCycleQty', models.IntegerField()),
                ('braintreeplanBillingCycleUnit', models.CharField(max_length=255)),
                ('braintreeplanBillingExpirationExists', models.BooleanField(default=False)),
                ('braintreeplanBillingExpirationInCycleQty', models.IntegerField(blank=True, null=True)),
                ('braintreeplanDiscountExists', models.BooleanField(default=False)),
                ('braintreeplanDiscountPercentage', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BraintreePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('braintrepricePrice', models.FloatField()),
                ('braintreemerchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymensor.BraintreeMerchant')),
                ('braintreeplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymensor.BraintreePlan')),
            ],
        ),
        migrations.CreateModel(
            name='BraintreeSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('braintreesubscriptionSubscriptionId', models.CharField(max_length=1024, null=True)),
                ('braintreesubscriptionSubscriptionStatus', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='assetMyMPrice',
        ),
        migrations.RemoveField(
            model_name='braintreecustomer',
            name='braintreecustomerMerchantAccId',
        ),
        migrations.RemoveField(
            model_name='braintreecustomer',
            name='braintreecustomerPlanId',
        ),
        migrations.RemoveField(
            model_name='braintreecustomer',
            name='braintreecustomerPrice',
        ),
        migrations.RemoveField(
            model_name='braintreecustomer',
            name='braintreecustomerSubscriptionId',
        ),
        migrations.RemoveField(
            model_name='braintreecustomer',
            name='braintreecustomerSubscriptionStatus',
        ),
        migrations.AddField(
            model_name='braintreecustomer',
            name='braintreecustomerCustomerCreatedDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='MyMPrice',
        ),
        migrations.AddField(
            model_name='braintreesubscription',
            name='braintreecustomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymensor.BraintreeCustomer'),
        ),
        migrations.AddField(
            model_name='braintreesubscription',
            name='braintreemerchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymensor.BraintreeMerchant'),
        ),
        migrations.AddField(
            model_name='braintreesubscription',
            name='braintreeplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymensor.BraintreePlan'),
        ),
    ]
