# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0065_auto_20170624_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='braintreesubscription',
            name='braintreemerchant',
        ),
        migrations.RemoveField(
            model_name='braintreesubscription',
            name='braintreeplan',
        ),
        migrations.AddField(
            model_name='braintreesubscription',
            name='braintreeprice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mymensor.BraintreePrice'),
            preserve_default=False,
        ),
    ]
