# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-25 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0066_auto_20170624_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='braintreesubscription',
            name='braintreesubscriptionPaymentInstrumentType',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
