# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0071_braintreesubscription_braintreesubscriptioncancelresultobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='braintreesubscription',
            name='braintreesubscriptionDBTimeStamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
