# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0072_braintreesubscription_braintreesubscriptiondbtimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='braintreesubscription',
            name='braintreesubscriptionPayMthdResultObject',
            field=models.CharField(max_length=32768, null=True),
        ),
    ]
