# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0075_auto_20170629_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='braintreesubscription',
            name='braintreesubscriptionCancelResultObject',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='braintreesubscription',
            name='braintreesubscriptionPayMthdResultObject',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='braintreesubscription',
            name='braintreesubscriptionResultObject',
            field=models.TextField(null=True),
        ),
    ]
