# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0076_auto_20170629_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='braintreesubscription',
            name='braintreesubscriptionPayPalBillingAgreementId',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='braintreesubscription',
            name='braintreesubscriptionPayPalEmail',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='braintreesubscription',
            name='braintreesubscriptionPaymentImageURL',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
