# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-09 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0078_mobileonlyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileonlyuser',
            name='mobileOnlyUserAuthUserId',
            field=models.IntegerField(null=True),
        ),
    ]
