# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0079_mobileonlyuser_mobileonlyuserauthuserid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileClientInstall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileClientInstallGUID', models.CharField(blank=True, max_length=1024, null=True)),
                ('mobileClientInstallDBTimeStamp', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymensor.Asset')),
            ],
        ),
    ]
