# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0080_mobileclientinstall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileclientinstall',
            name='mobileClientInstallDBTimeStamp',
        ),
        migrations.AddField(
            model_name='mobileclientinstall',
            name='mobileClientInstallCreationTimeStamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mobileclientinstall',
            name='mobileClientInstallLastAccessTimeStamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mobileclientinstall',
            name='mobileClientInstallOrderNumber',
            field=models.IntegerField(null=True),
        ),
    ]
