# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0081_auto_20170714_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='mediaDeviceId',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='mediaOriginalMymensorAccount',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
