# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0082_auto_20170717_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='mediaThumbnailStorageURL',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
