# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0083_media_mediathumbnailstorageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='vp',
            name='vpIsUsed',
            field=models.BooleanField(default=False),
        ),
    ]
