# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0085_media_mediaclienttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobileonlyuser',
            old_name='mobileOnlyUser',
            new_name='mobileOnlyUserOwner',
        ),
    ]
