# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0086_auto_20170807_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assetMyMensorPlan',
            field=models.CharField(choices=[('MyMensor Media', 'MyMensor Media'), ('MyMensor Media and Data', 'MyMensor Media and Data')], default='MyMensor Media and Data', max_length=50, verbose_name='MyMensor Plan'),
        ),
    ]
