# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-23 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0088_auto_20170823_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='braintreeplan',
            name='braintreeplanPlanMymensorTypeLastChangeDate',
            field=models.DateTimeField(null=True),
        ),
    ]
