# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-23 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0089_braintreeplan_braintreeplanplanmymensortypelastchangedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='braintreeplan',
            name='braintreeplanPlanMymensorTypeLastChangeDate',
        ),
        migrations.AddField(
            model_name='braintreesubscription',
            name='braintreesubscriptionPlanMymensorTypeLastChangeDate',
            field=models.DateTimeField(null=True),
        ),
    ]
