# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-24 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymensor', '0090_auto_20170823_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assetCountryGeoIp',
            field=models.CharField(max_length=50, null=True, verbose_name='Asset Country from GeoIp'),
        ),
        migrations.AddField(
            model_name='asset',
            name='assetGeoIpResponse',
            field=models.TextField(null=True, verbose_name='Response from MaxMind Service'),
        ),
        migrations.AddField(
            model_name='asset',
            name='assetIpGeoIp',
            field=models.CharField(max_length=50, null=True, verbose_name='Asset IP from GeoIp'),
        ),
    ]
