# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 17:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mymensor', '0091_auto_20171024_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=1024, null=True, verbose_name='Client Name')),
                ('clientNumber', models.IntegerField(null=True, verbose_name='Client Number')),
                ('clientDescription', models.CharField(max_length=1024, null=True, verbose_name='Client Description')),
                ('clientAddressLineOne', models.CharField(max_length=1024, null=True, verbose_name='Client Address Line One')),
                ('clientAddressLineTwo', models.CharField(max_length=1024, null=True, verbose_name='Client Address Line Two')),
                ('clientCountry', models.CharField(max_length=1024, null=True, verbose_name='Client Country')),
                ('clientOwner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=1024, null=True, verbose_name='Project Name')),
                ('projectNumber', models.IntegerField(null=True, verbose_name='Project Number')),
                ('projectDescription', models.CharField(max_length=1024, null=True, verbose_name='Project Description')),
                ('projecttAddressLineOne', models.CharField(max_length=1024, null=True, verbose_name='Project Address Line One')),
                ('projectAddressLineTwo', models.CharField(max_length=1024, null=True, verbose_name='Project Address Line Two')),
                ('projectCountry', models.CharField(max_length=1024, null=True, verbose_name='Project Country')),
                ('projectReportLayoutStyle', models.IntegerField(choices=[('standard', 'standard')], default='standard', verbose_name='Project Report Style')),
                ('projectInfoOne', models.CharField(max_length=1024, null=True, verbose_name='Info One')),
                ('projectInfoTwo', models.CharField(max_length=1024, null=True, verbose_name='Info Two')),
                ('projectInfoThree', models.CharField(max_length=1024, null=True, verbose_name='Info Three')),
                ('projectInfoFour', models.CharField(max_length=1024, null=True, verbose_name='Info Four')),
                ('projectInfoFive', models.CharField(max_length=1024, null=True, verbose_name='Info Five')),
                ('projectClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymensor.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportCode', models.CharField(max_length=50, null=True, verbose_name='Report Code')),
                ('reportCreationDate', models.DateTimeField(null=True)),
                ('reportTitle', models.CharField(default='Field Report', max_length=1024, verbose_name='Report Title')),
                ('reportFirstSectionTitle', models.CharField(default='People present during site visit', max_length=1024, verbose_name='Report First Section Title')),
                ('reportSecondSectionTitle', models.CharField(default='Items', max_length=1024, verbose_name='Report Second Section Title')),
                ('reportThirdSectionTitle', models.CharField(default='Terms and conditions', max_length=1024, verbose_name='Report Third Section Title')),
                ('reportTermsAndConditions', models.CharField(max_length=4096, null=True)),
                ('reportItemFirstColumnTitle', models.CharField(default='Item', max_length=50, verbose_name='Item First Column')),
                ('reportItemSecondColumnTitle', models.CharField(default='Description', max_length=50, verbose_name='Item Second Column')),
                ('reportItemThirdColumnTitle', models.CharField(default='Assigned to', max_length=50, verbose_name='Item Third Column')),
                ('reportCreator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reportProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymensor.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ReportItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportitemFirstSection', models.CharField(max_length=1024, null=True, verbose_name='First Section Text')),
                ('reportitemSecondSection', models.CharField(max_length=1024, null=True, verbose_name='Second Section Text')),
                ('reportitemThirdSection', models.CharField(max_length=1024, null=True, verbose_name='Third Section Text')),
                ('reportitemMedia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mymensor.Media')),
                ('reportitemReport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymensor.Report')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='assetCompanyLogo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetDciFrequencyUnit',
            field=models.CharField(choices=[('millis', 'millis'), ('hour', 'hour'), ('day', 'day'), ('week', 'week'), ('month', 'month')], default='millis', max_length=50, verbose_name='Master Capture frequency unit for VPs'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetDciFrequencyValue',
            field=models.IntegerField(default=20000, verbose_name='Master Minimum capture frequency value for VPs'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetDescription',
            field=models.CharField(max_length=1024, null=True, verbose_name='Company Name - your company name'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetOwnerDescription',
            field=models.CharField(max_length=1024, null=True, verbose_name='Company Description - your company description'),
        ),
    ]
